[package]
name = "omnic/default-baseplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.4"
Knit = "sleitnick/knit@1.7.0"
Promise = "evaera/promise@4.0.0"
Janitor = "howmanysmall/janitor@1.16.0"

[server-dependencies]
Datastore = "uiscript/suphis-datastore-module@0.2.0"